apiVersion: v1
kind: Service
metadata:
  name: dental-node-app-service
spec:
  type: LoadBalancer
  selector:
    app: dental-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
